["Fast Food Delight Unofficial Config"]
	#Generate Fast Food Shop Structures in Villages
	"Generate Structures" = true
	#Fast Food Shop Structure Weight, max is 50
	# Default: 25
	# Range: 0 ~ 50
	"Structure Weight" = 25
